CREATE TABLE "integration_settings" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"smtp_host" text,
	"smtp_port" integer,
	"smtp_user" text,
	"smtp_pass_encrypted" text,
	"email_from" text,
	"google_client_id" text,
	"google_client_secret_encrypted" text,
	"pusher_beams_instance_id" text,
	"pusher_beams_secret_key_encrypted" text,
	"pusher_app_id" text,
	"pusher_key" text,
	"pusher_secret_encrypted" text,
	"pusher_cluster" text,
	"storage_driver" text,
	"s3_bucket" text,
	"s3_region" text,
	"aws_access_key_id" text,
	"aws_secret_access_key_encrypted" text,
	"r2_bucket" text,
	"r2_account_id" text,
	"r2_access_key_id" text,
	"r2_secret_access_key_encrypted" text,
	"storage_public_base_url" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
